version: "3.9"

services:
  django-backend-db01-001:
    image: postgres:13.5-bullseye
    volumes:
      - kakeibo_backend:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: >
      bash -c "
        sed -i -e 's/force_text/force_str/' /usr/local/lib/$$(python --version | cut -d '.' -f 1,2 | tr 'A-Z' 'a-z' | tr -d ' ')/site-packages/django_pandas/utils.py
        git clone https://github.com/AbeYuki/kakeibo.git /codetmp
        cp -a /codetmp/. /code
        /tmp/local_settings.sh
        python /code/manage.py makemigrations 
        python /code/manage.py migrate 
        python /code/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - kakeibo_frontend:/code
    ports:
      - "8080:8000"
    depends_on:
      - django-backend-db01-001
volumes:
  kakeibo_backend:
  kakeibo_frontend: