apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io: django
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app.kubernetes.io/name: django
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - django
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - name: frontend-app01
        image: frontend-app01
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.15"
            memory: 245Mi
          limits:
            cpu: "0.5"
            memory: 526Mi
        command: ["/bin/bash", "-c"]
        args:
        - |
          patchesStrategicMerge
        env:
        - name: POSTGRES_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_DB
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: DEBUG
        ports:
        - name: django
          containerPort: 8000
        volumeMounts:
        - name: django
          mountPath: /code
      volumes:
      - name: django
        persistentVolumeClaim:
          claimName: frontend-app01
    