apiVersion: v1
kind: Service
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: postgres-django
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres-django
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: postgres-django
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db01
  labels:
    app.kubernetes.io/name: postgres-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-django
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-django
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - postgres-django
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker-registry
      containers:
      - image: backend-db01
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.15"
            memory: 245Mi
          limits:
            cpu: "0.5"
            memory: 526Mi
        name: backend-db01
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_DB
        - name: POSTGRES_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmap-django-variable01
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password             
        ports:
        - containerPort: 5432
          name: backend-db01
        volumeMounts:
        - name: backend-db01
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: backend-db01
        persistentVolumeClaim:
          claimName: backend-db01